{
 "title": "OpenVPN Server",
 "description": "OpenVPN Server status using Prometheus and OpenVPN exporter ",
 "tags": [
  "openvpn",
  "infra",
  "ops"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openvpnas_server_connected_clients{job=\"openvpnas-metrics\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openvpnas_server_connected_clients{})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openvpnas_subscription_maximum_client_connections{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last Updated since",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-openvpnas_subscription_status_update_time_seconds{job=\"openvpnas-metrics\"}"
    }
   ]
  },
  {
   "title": "Clients Connected",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Clients" }
   ],
   "targets": [
    {
     "expr": "sum(openvpnas_server_connected_clients)",
     "legendFormat": "Connected OpenVPN Clients"
    }
   ]
  }
 ]
}